### ISSUE TITLE
BpmnAutoLayout找不到

### ISSUE THREAD

**Issue by ucarpediem** [Lzgabel/camunda-bpmn-converter#1]
BpmnAutoLayout 是不是漏掉了？

**Comment by Lzgabel** [comment]
@ucarpediem 这个只是一个layout的工具，不用也无所谓，只是使布局更好看一点。
看下你是否能访问[中央仓库](https://search.maven.org/artifact/cn.lzgabel.layouter/bpmn-auto-layout/1.0.2/jar)，我看是能用的
