### ISSUE TITLE
大佬为什么不基于开源的仿钉钉流程设计器开发后端

### ISSUE THREAD

**Issue by StriverFeng** [lzgabel/camunda-bpmn-converter#5]
像这种https://gitee.com/StavinLi/Workflow 开源的只需要适配后端就可以了,前端不用考虑,使用范围会更广泛一些,另外大佬的代码可以拿来商用吗

**Comment by lzgabel** [comment]
🤔 没有get到你说的，前端不考虑什么意思

❓ 你的意思是想要，前端一套通用，后端随便搞？

**Comment by StriverFeng** [comment]
我的意思就是前端你不用弄,直接用开源的,而且开源的功能也比你这个多一些,你只需要适配开源前端就好了

**Comment by lzgabel** [comment]
@StriverFeng 抱歉，补充一下，目前这个项目首要目的主要是提供给大家一个 json 转 bpmn 的思路。仓库里的前端也仅仅是一个演示的 demo，目前没有足够多时间去一一实现

**Comment by StriverFeng** [comment]
ok
