### ISSUE TITLE
 源码中有一句代码应该可以替换一下

### ISSUE THREAD

**Issue by StriverFeng** [lzgabel/camunda-bpmn-converter#6]
在UserTaskProcessor中40行 有一句代码应该可以替换一下:
      
      UserTask userTask = (UserTask) createInstance(flowNodeBuilder, nodeType);//  

 替换为 UserTaskBuilder userTaskBuilder = flowNodeBuilder.userTask();  //官方有方法可以直接通过flowNodeBuilder创建userTask

类似的地方应该有几处

**Comment by StriverFeng** [comment]
类似的应该有几处

**Comment by lzgabel** [comment]
> 官方有方法可以直接通过flowNodeBuilder创建userTask

👋 Hi @StriverFeng。 `bpmn-model` 中有对应的方法这个我知道，之所以这么写是有原因。只是之前都是零零散散的搞。没时间弄完而已。
